language: node_js
node_js:
  - "0.12"
before_script:
  - 'bower install'
  - 'node_modules/protractor/bin/webdriver-manager update --standalone'
  - 'npm install grunt'
  - 'npm install grunt-cli'
  - 'npm install grunt-protractor-webdriver'
  - 'npm install grunt-protractor-runner'
  - 'npm install grunt-express-server'  
  - 'grunt'